/**
 * The User class was created for an implementation of a virtual game of
 * Gomoku. It stores a particular user's username, password, whether they are
 * online or offline, and in which game state they currently are.
 * 
 * @author Emily Shane
 * @author Ethan Wiederspan
 */

public class User {
	private String username;
	private String password;
	private int wins;
	private boolean online;
	private int gameState;	//0 = offline, 2 = in matchmaking, 3 = in game
	
	/**
	 * Constructor for User with known username and password (not anonymous)
	 * @param un the User's username
	 * @param pass the User's password
	 */
	public User(String un, String pass, String winCount){
		username = un;
		password = pass;
		wins = Integer.parseInt(winCount);
		setGameState(0);
	}
	
	/**
	 * Constructor for User with no known password (anonymous)
	 * @param un the User's username (generated by the ServerController)
	 */
	public User(String un){
		username = un;
	}
	
	/**
	 * Getter for this User's username
	 * @return this User's username
	 */
	public String getUN(){
		return username;
	}
	
	/**
	 * Get this User's password (called by the ServerModel to authenticate)
	 * @return this User's password
	 */
	public String getPass(){
		return password;
	}
	
	/**
	 * Setter for this User's online status
	 */
	public void setOnline(boolean oL){
		online = oL;
	}
	
	/**
	 * Getter for this User's online status (logged in)
	 * @return true if this User is logged in and false otherwise
	 */
	public boolean isOnline(){
		return online;
	}

	/**
	 * Getter for this User's current gameState
	 * @return the gameState
	 */
	public int getGameState() {
		return gameState;
	}

	/**
	 * Setter for this User's current gameState;
	 * @param gameState the gameState
	 */
	public void setGameState(int gameState) {
		this.gameState = gameState;
	}

	/**
	 * Setter for this User's wins field (the number of games they have won)
	 * @param winCount the number to set as the win count
	 */
	public void setWins(int winCount){
		wins = winCount;
	}

	/**
	 * Getter for the wins field (the number of games they have won)
	 * @return wins
	 */
	public int getWins(){
		return wins;
	}

	/**
	 * Adds one to this User's win count. Called when a player wins a game.
	 */
	public void incrementWins(){
		wins++;
	}
}